;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ensime-mouse-motion
	isearch-backward-regexp
	isearch-forward-regexp
	isearch-printing-char
	isearch-repeat-forward
	kill-region
	mark-sexp
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	))
